Repository gwdetchar/hveto, pull requests merged in 2019-11, with the labels that each got.

#132 Upgrade to bootstrap-4
  bin/hveto
  hveto/html.py
  hveto/tests/test_html.py
  hveto/triggers.py
  requirements.txt
  setup.cfg
Labels: enhancement, html

#130 Use gwdetchar.plot.texify for LaTeX escape characters
  bin/hveto
  hveto/plot.py
Labels: enhancement, figures

#135 Fix pages with null result
  bin/hveto
Labels: bug-fix, html

#136 Pass ranking statistic to omega scan selection
  bin/hveto
  hveto/core.py
  hveto/html.py
Labels: enhancement, omega-scans
